@extends("layouts.app")
@section("content")
@section('head_title', __('Terms and conditions | Beer baths in Prague') )
<header id="home" class="jumbotron bg-inverse text-center center-vertically">
<div class="container">
	<!--<img class="m-b-lg" src="{{ URL::asset('assets/img/logo.png') }}" title="{{__('Beer baths in Prague')}}" alt="{{__('Beer baths in Prague')}}" /><br>-->
	<h1 class="display-3 m-b-lg animated fadeInDown">{{__('Terms and conditions')}}</h1>
	<a class="btn btn-secondary-outline m-b-md animated fadeInDown slideble" href="#about" role="button">{{__('Lázně Pramen')}}</a>
	<!--
	<h2 class="m-b-lg animated fadeInUp">blablablba</h2>
	<a class="btn btn-secondary-outline m-b-md animated fadeInUp slideble" href="#reservation" role="button">{{__('Lázně Pramen Letná')}}</a>
	-->
	<div class="list-inline social-share animated fadeInUp">
		<a href="https://www.tripadvisor.com/Attraction_Review-g274707-d7377900-Reviews-Lazne_Pramen_Beer_and_Wine_spa-Prague_Bohemia.html" target="_blank"><img src="{{ URL::asset('assets/img/tripadvisor_white.svg') }}" title="{{__('Beer baths in Prague')}}" alt="{{__('Beer baths in Prague')}}" /><br>
		<span>#1 of 202 Spas & Wellness in Prague</p></span></a>
	</div>
</div>
</header>

<section id="about" class="section_about">
	<div class="container">
		<h2>{{__('Terms and conditions')}}</h2>
		<p>Servisní a reklamační řád společnosti ITS akciová společnost (dále jen „Servisní podmínky“):<br />I. OBECNÁ USTANOVENÍ, DEFINICE POJMŮ:</p>
<p>1. Servisní a reklamační řád společnosti ITS akciová společnost, IČ: 148 89 811, se sídlem: Praha 3, Vinohradská 184, zapsané v obchodním rejstříku vedeném Městským soudem v Praze, oddíl B, vložka 431 (dále jen „společnost“) upravuje zejména podmínky servisu, jakož i postup stran při reklamaci služeb, případně žádosti o pozáruční servis.<br />Uzavřením smlouvy o opravě či úpravě věci a předáním věci/zařízení (dále jen „zařízení“) do opravy objednatel souhlasí s těmito Servisními podmínkami a výslovně je přijímá s tím, že smlouva o opravě či úpravě věci se těmito Servisními podmínkami řídí. Servisní podmínky jsou nedílnou součástí smlouvy o opravě či úpravě věci uzavřené mezi objednatelem a společností, jako zhotovitelem, v souladu s ustanovením § 2586 a násl. zákona č. 89/2012 Sb., občanský zákoník, ve znění pozdějších předpisů (dále jen „občanský zákoník“).<br />Smlouvou o opravě či úpravě věci dle těchto Servisních podmínek se rozumí:<br />(i) zhotovitelem a objednatelem podepsaný Protokol o převzetí zařízení do opravy, jakož i<br />(ii) oprava či úprava zařízení v místě umístění zařízení u objednatele, nebo<br />(iii) doručení zařízení k opravě či úpravě společnosti objednatelem, přepravní službou nebo poštou na adresu servisního místa společnosti, uvedeného v čl. V. odst. 8 těchto Servisních podmínek, spolu s objednávkou objednatele, kdy objednatel vyjadřuje svoji vůli k uzavření smlouvy o opravě či úpravě věci vlastní objednávkou, přičemž smlouva je v tomto případě uzavřena okamžikem potvrzení takovéto objednávky ze strany společnosti, k němuž společnost připojí tyto Servisní podmínky nebo odkaz na webové stránky, kde jsou uloženy.<br />Objednatel (i) umožněním provedení servisního zásahu u objednatele, (ii) potvrzením Protokolu o převzetí zařízení do opravy nebo (iii) uzavřením smlouvy o opravě či úpravě věci na základě potvrzení vlastní objednávky objednatele ze strany společnosti dle předchozí věty potvrzuje svůj souhlas s těmito Servisními podmínkami s tím, že smlouva o opravě či úpravě věci se těmito Servisními podmínkami řídí.<br />Tyto Servisní podmínky platí pro servisní zásahy záručního servisu (tj. pro záruční servis zařízení dodaných společností i autorizovaný servis poskytovaný společností), jakož i pro smlouvy o opravě a úpravě věci uzavřené mezi společností a zákazníkem, jakožto objednatelem, a to na základě odkazu na tyto Servisní podmínky uvedeného zejména (i) v potvrzeném Protokolu o převzetí zařízení do opravy, (ii) v potvrzení objednávky, (iii) v potvrzení souhlasu s cenou servisního zásahu dle nabídky společnosti prostřednictvím e-mailové komunikace, případně (iv) v Pracovním listu potvrzeném ze strany objednatele, a to vždy okamžikem, kdy nastane kterákoli z těchto právních skutečností jako první.</p>
<p>2. Tyto Servisní podmínky se řídí právním řádem České republiky. Tyto Servisní podmínky se použijí na veškeré servisní zásahy společnosti a reklamace, nestanoví-li smlouva mezi společností a objednatelem něco jiného, anebo není-li společností v záručním/dodacím listu zařízení uvedeno jinak.</p>
<p>3. Zákazníkem se pro účely těchto Servisních podmínek rozumí fyzická nebo právnická osoba, která, jakožto objednatel, uzavřela se společností smlouvu o opravě a úpravě věci, případně, jejíž jinou objednávku servisního zásahu společnost při použití těchto Servisních podmínek potvrdila. Objednatelem dle těchto Servisních podmínek je míněn vždy též zákazník.<br />Spotřebitelem se pro účely těchto Servisních podmínek rozumí ve smyslu ustanovení § 419 občanského zákoníku každý člověk, který mimo rámec své podnikatelské činnosti nebo mimo rámec samostatného výkonu svého povolání uzavírá smlouvu s podnikatelem nebo s ním jinak jedná.<br />Podnikatelem ve smyslu ust. § 420 občanského zákoníku je ten, kdo samostatně vykonává na vlastní účet a odpovědnost výdělečnou činnost živnostenským nebo obdobným způsobem se záměrem činit tak soustavně za účelem dosažení zisku. Za podnikatele se považuje pro účely ochrany spotřebitele také každá osoba, která uzavírá smlouvy související s vlastní obchodní, výrobní nebo obdobnou činností či při samostatném výkonu svého povolání, popřípadě osoba, která jedná jménem nebo na účet podnikatele.<br />Objednatelem se pro účely těchto Servisních podmínek rozumí (i) zákazník, jemuž bylo zařízení dodáno společností nebo (ii) zákazník používající zařízení dodané třetí osobou, který<br />(i) předal společnosti zařízení k poskytnutí servisního zásahu záručního servisu na zařízení dodaném společností<br />(ii) předal společnosti zařízení k poskytnutí servisního zásahu autorizovaného servisu<br />(iii) uzavřel se společností smlouvu o opravě a úpravě věci<br />(iv) si u společnosti objednal pozáruční servis zařízení či<br />(v) si jinak (způsobem jak je definován v čl. I. těchto Servisních podmínek) objednal u společnosti servisní zásah<br />Zařízením se rozumí jakékoli IT zařízení, které (i) nese originální označení značky „Lenovo“, „IBM“, „Apple“, „Toshiba“ nebo zařízení dodané společností a (ii) jež bylo předáno společnosti k servisnímu zásahu.<br />Záručním servisem je oprava zařízení v rámci společností poskytnuté záruky za jakost, přesněji vymezená společností v záručním/dodacím listu, realizovaná servisem společnosti na základě řádné reklamace zařízení zákazníkem a dle těchto Servisních podmínek.<br />Záručním servisem dle těchto Servisních podmínek je též oprava zařízení realizovaná společností, jakožto autorizovaným servisním střediskem (autorizovaným servisem) v rámci záručního servisu výrobců značky „Lenovo“, „IBM“, „Apple“ a „Toshiba“ (dále jen „autorizovaný servis“).<br />Pozáručním servisem je jakákoli oprava nebo úprava zařízení vykonávaná na základě žádosti objednatele mimo nebo nad rámec záruky garantované záručním listem.</p>
<p>4. Servisní podmínky jsou platné v aktuálním znění a jsou dostupné na webových stránkách společnosti www.its.cz/produkty-a-sluzby a služby jakožto nedílná součást smlouvy o opravě či úpravě věci platí Servisní podmínky aktuální (účinné) k datu uzavření smlouvy o opravě či úpravě věci.</p>
<p>5. Kontaktní údaje: ITS akciová společnost, IČ: 148 89 811, se sídlem: Praha 3, Vinohradská 184, tel.: 255 772 333.</p>
	</div>
</section>
@endsection